version: "3"
services:
    jekyll:
        build: .
        command: jekyll serve --watch --incremental --force_polling
        ports:
            - 4000:4000
        volumes:
            - ./:/srv/jekyll
